# Generated by Django 2.1.3 on 2018-11-19 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pacientes_photos'),
        ),
    ]
